EmployeeManagementSystem/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using EmployeeManagementSystem.Models;
using EmployeeManagementSystem.Infrastructure; 
using System.Security.Claims;



namespace EmployeeManagementSystem.Controllers
{
     public class CompaniesController : Controller

    {
       string userName;
        int userId;
        ICRUDRepository<Company, int> _repository;
        public SendServiceBusMessage _SendServiceBusMessage;
        public CompaniesController( ICRUDRepository<Company, int> repository, SendServiceBusMessage sendServiceBusMessage)
        { 
        _repository = repository;
         _SendServiceBusMessage = sendServiceBusMessage;
        }
        public ActionResult<IEnumerable<Company>> Get()
        {
            try
            {
            var items = _repository.GetAll(); 
            return View(items);
            }
        catch(Exception ex)
            {
                throw;
            }
    
        }
        //Add the EFCore.SQLServer package 
        //dotnet add package Microsoft.EntityFrameworkCore.SqlServer


         //URL: /api/employees/1
         //try with id parameter values between 1 and 9

         [HttpGet("{id}")]
         public ActionResult<Company> GetDetails(int id)
        {
            try{
            var item = _repository.GetDetails(id);
            if(item==null)
            return NotFound();
            return item;
            }
            catch (Exception ex)
            {
                throw;
            }
        }
        public IActionResult Create()
        {
            return View();
        }
        [Microsoft.AspNetCore.Authorization.Authorize()]

        [HttpPost]
        public async Task <ActionResult<Company>> Create(Company cmp)
       {
            if (!ModelState.IsValid)
                //throw new ArgumentException("Not found");
                userName = HttpContext.User.FindFirst(ClaimTypes.Name).Value;
             userId = Convert.ToInt32("0" + HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var role = Convert.ToString(HttpContext.User.FindFirst(ClaimTypes.Role).Value);
            if (role != "admin")
            {
                return Unauthorized();
            }
            if (userId == 0) return BadRequest();
            try
            {
                if (cmp == null) return BadRequest();
                _repository.Create(cmp);
                await _SendServiceBusMessage.sendServiceBusMessage(new ServiceBusMessageData
                {
                    CompanyName = cmp.CompanyName,
                    action = "Create",
                    actionMessage = "Company Created Successfully"
                });
                return Redirect("/companies/Get");
            }
            catch (Exception ex)
            {
                throw;
            }
    
  
            
       }
        public IActionResult update(int Id)
        {
            Company cmp = _repository.GetDetails(Id);
            if (cmp == null)
            {
                return BadRequest();
            }
            else
            {
                return View(cmp);
            }
        }
        [Microsoft.AspNetCore.Authorization.Authorize()]

       [HttpPost]
       public async Task <ActionResult<Company>> update(Company cmp)
       {
            userName = HttpContext.User.FindFirst(ClaimTypes.Name).Value;
            userId = Convert.ToInt32("0" + HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var role = Convert.ToString(HttpContext.User.FindFirst(ClaimTypes.Role).Value);
            if(role!="admin") 
            {
                return Unauthorized();
            }
            if(userId==0) return BadRequest();
            // if(id==0)  return BadRequest();
            try 
            { 
                if (cmp == null)
                    return BadRequest();
                _repository.update(cmp);
                    await _SendServiceBusMessage.sendServiceBusMessage(new ServiceBusMessageData
                    {
                        CompanyName = cmp.CompanyName,
                        action = "update",
                        actionMessage = "Company Updated Successfully"
                    });
                    ViewBag.Message = string.Format("Updated Successfully");
                return View(cmp);
             }
            catch (Exception ex)
            {
                throw;
            }

       }
        public IActionResult Delete(int Id)
        {
            Company cmp = _repository.GetDetails(Id);
            if (cmp == null)
            {
                return BadRequest();
            }
            else
            {
                return View(cmp);
            }
        }
        [Microsoft.AspNetCore.Authorization.Authorize()]
        [HttpPost]
        public async Task <ActionResult<Company>> Delete(int id,Company cmp)
        {

            userName = HttpContext.User.FindFirst(ClaimTypes.Name).Value;
            userId = Convert.ToInt32("0" + HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var role = Convert.ToString(HttpContext.User.FindFirst(ClaimTypes.Role).Value);
            if (role != "admin")
            {
                return Unauthorized();
            }
            //end of the code inclusion. 
            if (userId == 0) return BadRequest();
            try
            {
                _repository.Delete(id);
                await _SendServiceBusMessage.sendServiceBusMessage(new ServiceBusMessageData
                {
                    CompanyName = cmp.CompanyName,
                    action = "Delete",
                    actionMessage = "Company Deleted Successfully"
                });
                ViewBag.Message = string.Format("Company Deleted Successfully");
                return Redirect("/companies/Get");
            }
            catch (Exception ex)
            {
                throw;
            }
    
        }


     }

}

EmployeeManagementSystem/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using EmployeeManagementSystem.Models;
using EmployeeManagementSystem.Infrastructure;
using System.Security.Claims;



namespace EmployeeManagementSystem.Controllers
{
    public class UsersController : Controller
    {
        string userName;
        int userId;
        ICRUDRepository<User, int> _repository;
        public SendServiceBusMessage _SendServiceBusMessage;
        public UsersController(ICRUDRepository<User, int> repository, SendServiceBusMessage sendServiceBusMessage)
        {
            _repository = repository;
            _SendServiceBusMessage = sendServiceBusMessage;
        }
        public ActionResult<IEnumerable<User>> Get()
        {
            try
            {
                var items = _repository.GetAll();
                //return items.ToList();
                return View(items);
            }
            catch(Exception ex)
            {
                throw;
            }
        }

        // [HttpGet("Users")]
        // public Models.User GetUser()
        // {
        //     Models.User obj = new Models.User{
        //         Id=1,
        //         UserName="Jyo",
        //         UserAddress="Banglore",
        //         UserType="No",
        //         Password="AH6SKJ",
        //     };
        //    return obj;  
        // } 

             [HttpGet("{id}")]
           public ActionResult<User> GetDetails(int id)
           {
                try
                {
                    var item = _repository.GetDetails(id);
                    if (item == null)
                        return NotFound();

                    return item;
                }
                catch(Exception ex)
                {
                    throw;
                }

           }
        public IActionResult Create()
        {
            return View();
        }
        [Microsoft.AspNetCore.Authorization.Authorize()]

        [HttpPost]
        
           public async Task <ActionResult<User>> Create(User usr)
           {
            userName = HttpContext.User.FindFirst(ClaimTypes.Name).Value;
            userId = Convert.ToInt32("0" + HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var role = Convert.ToString(HttpContext.User.FindFirst(ClaimTypes.Role).Value);
                if(role!="newemployee") 
                {
                    return Unauthorized();
                }
                try
               { 
                    if(userId==0) return BadRequest();
                       if(usr==null)
                       return BadRequest();

                   _repository.Create(usr);

                    await _SendServiceBusMessage.sendServiceBusMessage(new ServiceBusMessageData
                    {
                        UserName = usr.UserName,
                        action = "Create",
                        actionMessage = "User Created Successfully"
                    });
                    return Redirect("/Users/Get");
                }
                catch (Exception ex)
                {
                    throw;
                }
                   return usr;
    
               
           } 

           //[HttpPut("update/{id}")]
        public IActionResult update(int Id)
        {
            User usr = _repository.GetDetails(Id);
            if (usr == null)
            {
                return BadRequest();
            }
            else
            {
                return View(usr);
            }
        }
        [Microsoft.AspNetCore.Authorization.Authorize()]

        [HttpPost]
          public async Task <ActionResult<User>> update(int id,User usr)
           {

                userName = HttpContext.User.FindFirst(ClaimTypes.Name).Value;
                userId = Convert.ToInt32("0" + HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
                var role = Convert.ToString(HttpContext.User.FindFirst(ClaimTypes.Role).Value);
                if (role != "admin")
                {
                    return Unauthorized();
                }
                if (userId == 0) return BadRequest();
            // if(id==0)  return BadRequest();
                try
                {
                    if (usr == null)
                        return BadRequest();
                    if (id == 0) return BadRequest();
                    _repository.update(usr);
                    await _SendServiceBusMessage.sendServiceBusMessage(new ServiceBusMessageData
                    {
                        UserName = usr.UserName,
                        action = "update",
                        actionMessage = "User Updated Successfully"
                    });
                    ViewBag.Message = string.Format("Updated Successfully");
                    return View(usr);
                }
                catch (Exception ex)
                   {
                        throw;
                 }
                    
                
           
          }
            //[HttpDelete("remove/{id}")]

        public IActionResult Delete(int Id)
        {
            User usr = _repository.GetDetails(Id);
            if (usr == null)
            {
                return BadRequest();
            }
            else
            {
                return View(usr);
            }
        }
        [Microsoft.AspNetCore.Authorization.Authorize()]
        [HttpPost]
         public async Task <ActionResult<User>> Delete(int id, User usr)
           {
                userName = HttpContext.User.FindFirst(ClaimTypes.Name).Value;
                userId = Convert.ToInt32("0" + HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
                var role = Convert.ToString(HttpContext.User.FindFirst(ClaimTypes.Role).Value);
                if(role!="admin") 
                {
                    return Unauthorized();
                }
                if(userId==0) return BadRequest();
                try
               { 
                       _repository.Delete(id);
                    await _SendServiceBusMessage.sendServiceBusMessage(new ServiceBusMessageData
                    {
                        UserName = usr.UserName,
                        action = "Delete",
                        actionMessage = "User Deleted Successfully"
                    });
                    ViewBag.Message = string.Format("User Deleted Successfully");
                    return Redirect("/Users/Get");
               }
                catch (Exception ex)
                {
                    throw;
                }
               // return Ok();
           
           }

        
    }
}

EmployeeManagementSystem/Views/Companies/Create.cshtml
@model EmployeeManagementSystem.Models.Company

@{
    ViewData["Title"] = "Create";
}

<form method="post" asp-controller="Companies" asp-action="Create">
    <input asp-for="CompanyId" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h1 class="text-info p1-3">Create Company</h1>
        </div>
        <div class="row">
            <div class="col-8">
                 <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="CompanyName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CompanyName" class="form-control" />
                        <span asp-validation-for="CompanyName" class="text-danger"></span>
                    </div>
                </div>
                 <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="CompanyAddress"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CompanyAddress" class="form-control" />
                        <span asp-validation-for="CompanyAddress" class="text-danger"></span>
                    </div>
                </div>
                 <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="City"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="City" class="form-control" />
                        <span asp-validation-for="City" class="text-danger"></span>
                    </div>
                </div>
                 <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="PostalCode"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="PostalCode" class="form-control" />
                        <span asp-validation-for="PostalCode" class="text-danger"></span>
                    </div>
                </div>
                 <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Country"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Country" class="form-control" />
                        <span asp-validation-for="Country" class="text-danger"></span>
                    </div>
                </div>
                 <div class="form-group row">
                    @*<div class="col-6 offset-4 row">*@
                    <div class="col-4 offset-4">
                        <input type="submit" class="btn btn-info w-100" value="Create" />
                    </div>
                   @*<div class="col">
                        @if (ViewBag.Message != null)
                        {
                            //<a class="nav-link text-dark btn-primary font-weight-bold" style="margin: 10px; background-color: #ffdd0f;top: 2px " asp-area="" asp-controller="Admin" asp- asp-action="Get">Get All Products</a>
                            <a class="nav-link text-dark btn-primary font-weight-bold" style="position: relative; margin: 10px; background-color: #ff8d00;float: right" asp-area="" asp-controller="Admin" asp- asp-action="Get">Get All Products</a>
                            <script type="text/javascript">
                                                window.onload = function () {
                                                alert("@ViewBag.Message");
                                                };
                            </script>
                        }
                    </div>*@
                    @*</div>*@
                </div>
            </div>
            <div class="col-4">
            </div>
        </div>
    </div>
</form>

EmployeeManagementSystem/Views/Companies/Delete.cshtml
@model EmployeeManagementSystem.Models.Company
@{
    ViewData["Title"] = "Delete";
}

<form method="post" asp-controller="Companies" asp-action="Delete">
   @* <input asp-for="CompanyId" hidden />*@
    <div class="border p-3">
        <div class="form-group row">
            <h1 class="text-info p1-3">Delete Company</h1>
        </div>
        <div class="row">
            <div class="col-8">
                 <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="CompanyId"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CompanyId" class="form-control" />
                        <span asp-validation-for="CompanyId" class="text-danger"></span>
                    </div>
                </div>
                 <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="CompanyName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CompanyName" class="form-control" />
                        <span asp-validation-for="CompanyName" class="text-danger"></span>
                    </div>
                </div>
                 <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="CompanyAddress"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CompanyAddress" class="form-control" />
                        <span asp-validation-for="CompanyAddress" class="text-danger"></span>
                    </div>
                </div>
                 <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="City"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="City" class="form-control" />
                        <span asp-validation-for="City" class="text-danger"></span>
                    </div>
                </div>
                 <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="PostalCode"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="PostalCode" class="form-control" />
                        <span asp-validation-for="PostalCode" class="text-danger"></span>
                    </div>
                </div>
                 <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Country"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Country" class="form-control" />
                        <span asp-validation-for="Country" class="text-danger"></span>
                    </div>
                </div>
                 <div class="form-group row">
                    @*<div class="col-6 offset-4 row">*@
                    <div class="col-4 offset-4">
                        <input type="submit" class="btn btn-info w-100" value="Delete" />
                    </div>
                   <div class="col">
                            @if (ViewBag.Message != null)
                            {
                                @*<a class="nav-link text-dark btn-primary font-weight-bold" style="margin: 10px; background-color: #ffdd0f;top: 2px " asp-area="" asp-controller="Admin" asp- asp-action="Get">Get Employees</a>*@
                                <a class="nav-link text-dark btn-primary font-weight-bold" style="position: relative; margin: 10px; background-color: #ff8d00;float: right" asp-area="" asp-controller="Companies" asp- asp-action="Get">Get Company</a>
                                <script type="text/javascript">
                                                    window.onload = function () {
                                                    alert("@ViewBag.Message");
                                                    };
                                </script>
                            }
                        </div>
                    @*</div>*@
                </div>
            </div>
            <div class="col-4">
            </div>
        </div>
    </div>
</form>

EmployeeManagementSystem/Views/Companies/Get.cshtml
@model IEnumerable<EmployeeManagementSystem.Models.Company>

@{
    ViewData["Title"] = "Get";
}

<div style="position: absolute; top: 0; right: 0; width: 180px; text-align:right;">
    <button><h3><a class="nav-link text-dark btn-primary font-weight-bold" style="position: relative; margin: 10px; background-color: #FFFFFF; float: left" asp-area="" asp-controller="Account" asp-action="SignOut">Company SignOut</a></h3></button>
</div>
<br />

    <div class="col-6">
        <h2 class="text-primary">Company List</h2>
    </div>
    <div class="container">
        <div class="btn-group">
            </h3><button type="button" class="nav-link text-dark btn-primary font-weight-bold" style="margin: 1px; background-color: #00b9ff;float: initial" asp-area="" asp-controller="Companies" asp- asp-action="Get">Company</button></h3>
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <a class="nav-link text-dark btn-primary font-weight-bold" style="background-color: #FFFFFF;float: left" asp-area="" asp-controller="Employees" asp- asp-action="Get">Employee</a>
                <a class="nav-link text-dark btn-primary font-weight-bold" style="background-color: #FFFFFF;float: left" asp-area="" asp-controller="Projects" asp- asp-action="Get"> Project</a>
                <a class="nav-link text-dark btn-primary font-weight-bold" style="background-color: #FFFFFF;float: left" asp-area="" asp-controller="Departments" asp- asp-action="Get"> Department</a>
                <a class="nav-link text-dark btn-primary font-weight-bold" style="background-color: #FFFFFF;float: left" asp-area="" asp-controller="Users" asp- asp-action="Get"> User</a>
            </ul>
        </div>
    </div>

    <div class="container p-3">
        <div class="row pt-10">
            @*<div class="col-6">
                    <h4>Employee List</h4>
                </div >*@
            <div class="col-12">
                <a class="nav-link text-dark btn-primary font-weight-bold" style="margin: 10px; background-color: #00b9ff;float: right" asp-area="" asp-controller="Companies" asp- asp-action="Create">Create New Companies</a>
            </div>
        </div>
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered table-striped" style="width:100%">
                <thead>
                    <tr>
                        <th>
                            CompanyId
                        </th>
                        <th>
                            CompanyName
                        </th>
                        <th>
                            CompanyAddress
                        </th>
                        <th>
                            City
                        </th>
                        <th>
                            PostalCode
                        </th>
                        <th>
                            Country
                        </th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var obj in Model)
                    {
                        <tr>
                            <td width="10%">@obj.CompanyId</td>
                            <td width="30%">@obj.CompanyName</td>
                            <td width="20%">@obj.CompanyAddress</td>
                            <td width="20%">@obj.City</td>
                            <td width="10%">@obj.PostalCode</td>
                            <td width="40%">@obj.Country</td>
                            <td class="text-center">
                                <div class="w-75 btn-group" role="group">
                                    <a asp-controller="Companies" asp-route-Id="@obj.CompanyId" asp-action="update" class="btn btn-primary mx-1">
                                        <i class="fas fa-edit"></i> Edit
                                    </a>
                                    <a asp-controller="Companies" asp-route-Id="@obj.CompanyId" asp-action="Delete" class="btn btn-danger mx-3">
                                        <i class="far fa-trash-alt"></i> Delete
                                    </a>
                                </div>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>

EmployeeManagementSystem/Views/Companies/update.cshtml
@model EmployeeManagementSystem.Models.Company

@{
    ViewData["Title"] = "update";
}

<form method="post" asp-controller="Companies" asp-action="update">
    <input asp-for="CompanyId" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h1 class="text-info p1-3">Edit Company</h1>
        </div>
        <div class="row">
            <div class="col-8">
               
                 <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="CompanyName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CompanyName" class="form-control" />
                        <span asp-validation-for="CompanyName" class="text-danger"></span>
                    </div>
                </div>
                 <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="CompanyAddress"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CompanyAddress" class="form-control" />
                        <span asp-validation-for="CompanyAddress" class="text-danger"></span>
                    </div>
                </div>
                 <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="City"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="City" class="form-control" />
                        <span asp-validation-for="City" class="text-danger"></span>
                    </div>
                </div>
                 <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="PostalCode"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="PostalCode" class="form-control" />
                        <span asp-validation-for="PostalCode" class="text-danger"></span>
                    </div>
                </div>
                 <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Country"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Country" class="form-control" />
                        <span asp-validation-for="Country" class="text-danger"></span>
                    </div>
                </div>
                 <div class="form-group row">
                    @*<div class="col-6 offset-4 row">*@
                    <div class="col-4 offset-4">
                        <input type="submit" class="btn btn-info w-100" value="Update" />
                    </div>
                   <div class="col">
                            @if (ViewBag.Message != null)
                            {
                                @*<a class="nav-link text-dark btn-primary font-weight-bold" style="margin: 10px; background-color: #ffdd0f;top: 2px " asp-area="" asp-controller="Admin" asp- asp-action="Get">Get Employees</a>*@
                                <a class="nav-link text-dark btn-primary font-weight-bold" style="position: relative; margin: 10px; background-color: #ff8d00;float: right" asp-area="" asp-controller="Companies" asp- asp-action="Get">Get Company</a>
                                <script type="text/javascript">
                                                    window.onload = function () {
                                                    alert("@ViewBag.Message");
                                                    };
                                </script>
                            }
                        </div>
                    @*</div>*@
                </div>
            </div>
            <div class="col-4">
            </div>
        </div>
    </div>
</form>