EmployeeManagementSystem/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using EmployeeManagementSystem.Models;
using EmployeeManagementSystem.Infrastructure;
using System.Security.Claims;

namespace EmployeeManagementSystem.Controllers
{
    public class ProjectsController : Controller
    {
        string userName;
        int userId;
        ICRUDRepository<Project, int> _repository;
        public SendServiceBusMessage _SendServiceBusMessage;
        public ProjectsController(ICRUDRepository<Project, int> repository, SendServiceBusMessage sendServiceBusMessage)
        {
            _repository = repository;
            _SendServiceBusMessage = sendServiceBusMessage;
        }
                public ActionResult<IEnumerable<Project>> Get()
                {
                   var items = _repository.GetAll();
                   return View(items);
                }

        //  [HttpGet("project")]
        //         public Models.Projects GetProject()
        //         {
        //             Models.Projects obj = new Models.Projects{
        //                 ProjectId=1,
        //                 ProjectName="R",
        //                 ProjectDescription="SSSS",
        //             };
        //            return obj;  

        [HttpGet("{id}")]
        public ActionResult<Project> GetDetails(int id)
        {
            try
            {
                var item = _repository.GetDetails(id);
                if (item == null)
                    return NotFound();

                return item;
            }

            catch (Exception ex)
            {
                throw;
            }
        }

          //[HttpPost("addnew")]
        public IActionResult Create()
        {
            return View();
        }
        [Microsoft.AspNetCore.Authorization.Authorize()]

        [HttpPost]

        public async Task <ActionResult<Project>> Create(Project prj)
          {
            if (!ModelState.IsValid)
                //throw new ArgumentException("Not found");
                userName = HttpContext.User.FindFirst(ClaimTypes.Name).Value;
            userId = Convert.ToInt32("0" + HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var role = Convert.ToString(HttpContext.User.FindFirst(ClaimTypes.Role).Value);
            if (role != "admin")
            {
                return Unauthorized();
            }
            if (userId == 0) return BadRequest();
            try
            {

                if (prj == null)
                    return BadRequest();
                _repository.Create(prj);
                await _SendServiceBusMessage.sendServiceBusMessage(new ServiceBusMessageData
                {
                    ProjectName = prj.ProjectName,
                    action = "Create",
                    actionMessage = "Project Created Successfully"
                });
                return Redirect("/Projects/Get");
                return View(prj);
            }
            catch(Exception ex)
            {
                throw;
            }
        }

        // [HttpPut("update/{id}")]
        public IActionResult update(int Id)
        {
            Project prj = _repository.GetDetails(Id);
            if (prj == null)
            {
                return BadRequest();
            }
            else
            {
                return View(prj);
            }
        }
        [Microsoft.AspNetCore.Authorization.Authorize()]

        [HttpPost]

        public async Task <ActionResult<Project>> update(int id, Project prj)
          {
            userName = HttpContext.User.FindFirst(ClaimTypes.Name).Value;
            userId = Convert.ToInt32("0" + HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var role = Convert.ToString(HttpContext.User.FindFirst(ClaimTypes.Role).Value);
            if (role != "admin")
            {
                return Unauthorized();
            }
            if (userId == 0) return BadRequest();
            try
            {

                if (prj == null)
                    return BadRequest();
                if (id == 0) return BadRequest();
                _repository.update(prj);
                await _SendServiceBusMessage.sendServiceBusMessage(new ServiceBusMessageData
                {
                    ProjectName = prj.ProjectName,
                    action = "update",
                    actionMessage = "project Updated Successfully"
                });
                ViewBag.Message = string.Format("Updated Successfully");
                return View(prj);
            }
            catch (Exception ex)
            {
                throw;
            }

        }
        public IActionResult Delete(int Id)
        {
            Project prj = _repository.GetDetails(Id);
            if (prj == null)
            {
                return BadRequest();
            }
            else
            {
                return View(prj);
            }
        }
        [Microsoft.AspNetCore.Authorization.Authorize()]
        [HttpPost]
        public async Task<ActionResult<Project>> Delete(int id, Project prj)
        {
            ;
            userName = HttpContext.User.FindFirst(ClaimTypes.Name).Value;
            userId = Convert.ToInt32("0" + HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var role = Convert.ToString(HttpContext.User.FindFirst(ClaimTypes.Role).Value);
            if (role != "admin")
            {
                return Unauthorized();
            }
            //end of the code inclusion. 
            if (userId == 0) return BadRequest();
            try
            {
                _repository.Delete(id);
                await _SendServiceBusMessage.sendServiceBusMessage(new ServiceBusMessageData
                {
                    ProjectName = prj.ProjectName,
                    action = "Delete",
                    actionMessage = "Project Deleted Successfully"
                });
                ViewBag.Message = string.Format("Project Deleted Successfully");
                return Redirect("/projects/Get");
            }
            catch (Exception ex)
            {
                throw;
            }

        }


    }
}

EmployeeManagementSystem/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using EmployeeManagementSystem.Models;
using EmployeeManagementSystem.Infrastructure;
using System.Security.Claims;



namespace EmployeeManagementSystem.Controllers
{
    public class UsersController : Controller
    {
        string userName;
        int userId;
        ICRUDRepository<User, int> _repository;
        public SendServiceBusMessage _SendServiceBusMessage;
        public UsersController(ICRUDRepository<User, int> repository, SendServiceBusMessage sendServiceBusMessage)
        {
            _repository = repository;
            _SendServiceBusMessage = sendServiceBusMessage;
        }
        public ActionResult<IEnumerable<User>> Get()
        {
            try
            {
                var items = _repository.GetAll();
                //return items.ToList();
                return View(items);
            }
            catch(Exception ex)
            {
                throw;
            }
        }

        // [HttpGet("Users")]
        // public Models.User GetUser()
        // {
        //     Models.User obj = new Models.User{
        //         Id=1,
        //         UserName="Jyo",
        //         UserAddress="Banglore",
        //         UserType="No",
        //         Password="AH6SKJ",
        //     };
        //    return obj;  
        // } 

             [HttpGet("{id}")]
           public ActionResult<User> GetDetails(int id)
           {
                try
                {
                    var item = _repository.GetDetails(id);
                    if (item == null)
                        return NotFound();

                    return item;
                }
                catch(Exception ex)
                {
                    throw;
                }

           }
        public IActionResult Create()
        {
            return View();
        }
        [Microsoft.AspNetCore.Authorization.Authorize()]

        [HttpPost]
        
           public async Task <ActionResult<User>> Create(User usr)
           {
            userName = HttpContext.User.FindFirst(ClaimTypes.Name).Value;
            userId = Convert.ToInt32("0" + HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var role = Convert.ToString(HttpContext.User.FindFirst(ClaimTypes.Role).Value);
                if(role!="newemployee") 
                {
                    return Unauthorized();
                }
                try
               { 
                    if(userId==0) return BadRequest();
                       if(usr==null)
                       return BadRequest();

                   _repository.Create(usr);

                    await _SendServiceBusMessage.sendServiceBusMessage(new ServiceBusMessageData
                    {
                        UserName = usr.UserName,
                        action = "Create",
                        actionMessage = "User Created Successfully"
                    });
                    return Redirect("/Users/Get");
                }
                catch (Exception ex)
                {
                    throw;
                }
                   return usr;
    
               
           } 

           //[HttpPut("update/{id}")]
        public IActionResult update(int Id)
        {
            User usr = _repository.GetDetails(Id);
            if (usr == null)
            {
                return BadRequest();
            }
            else
            {
                return View(usr);
            }
        }
        [Microsoft.AspNetCore.Authorization.Authorize()]

        [HttpPost]
          public async Task <ActionResult<User>> update(int id,User usr)
           {

                userName = HttpContext.User.FindFirst(ClaimTypes.Name).Value;
                userId = Convert.ToInt32("0" + HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
                var role = Convert.ToString(HttpContext.User.FindFirst(ClaimTypes.Role).Value);
                if (role != "admin")
                {
                    return Unauthorized();
                }
                if (userId == 0) return BadRequest();
            // if(id==0)  return BadRequest();
                try
                {
                    if (usr == null)
                        return BadRequest();
                    if (id == 0) return BadRequest();
                    _repository.update(usr);
                    await _SendServiceBusMessage.sendServiceBusMessage(new ServiceBusMessageData
                    {
                        UserName = usr.UserName,
                        action = "update",
                        actionMessage = "User Updated Successfully"
                    });
                    ViewBag.Message = string.Format("Updated Successfully");
                    return View(usr);
                }
                catch (Exception ex)
                   {
                        throw;
                 }
                    
                
           
          }
            //[HttpDelete("remove/{id}")]

        public IActionResult Delete(int Id)
        {
            User usr = _repository.GetDetails(Id);
            if (usr == null)
            {
                return BadRequest();
            }
            else
            {
                return View(usr);
            }
        }
        [Microsoft.AspNetCore.Authorization.Authorize()]
        [HttpPost]
         public async Task <ActionResult<User>> Delete(int id, User usr)
           {
                userName = HttpContext.User.FindFirst(ClaimTypes.Name).Value;
                userId = Convert.ToInt32("0" + HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
                var role = Convert.ToString(HttpContext.User.FindFirst(ClaimTypes.Role).Value);
                if(role!="admin") 
                {
                    return Unauthorized();
                }
                if(userId==0) return BadRequest();
                try
               { 
                       _repository.Delete(id);
                    await _SendServiceBusMessage.sendServiceBusMessage(new ServiceBusMessageData
                    {
                        UserName = usr.UserName,
                        action = "Delete",
                        actionMessage = "User Deleted Successfully"
                    });
                    ViewBag.Message = string.Format("User Deleted Successfully");
                    return Redirect("/Users/Get");
               }
                catch (Exception ex)
                {
                    throw;
                }
               // return Ok();
           
           }

        
    }
}

EmployeeManagementSystem/Views/Users/Create.cshtml
@*@{
        ViewData["Title"] = "Create";
    }

    <h1>Create</h1>*@

@model EmployeeManagementSystem.Models.User

@{
    ViewData["Title"] = "Create";
}

<form method="post" asp-controller="Users" asp-action="Create">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h1 class="text-info p1-3">Create User</h1>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="UserName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="UserName" class="form-control" />
                        <span asp-validation-for="UserName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Password"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                </div>
                
                <div class="form-group row">
                    @*<div class="col-6 offset-4 row">*@
                    <div class="col-4 offset-4">
                        <input type="submit" class="btn btn-info w-100" value="Create" />
                    </div>
                    @*<div class="col">
                            @if (ViewBag.Message != null)
                            {
                                //<a class="nav-link text-dark btn-primary font-weight-bold" style="margin: 10px; background-color: #ffdd0f;top: 2px " asp-area="" asp-controller="Admin" asp- asp-action="Get">Get All Products</a>
                                <a class="nav-link text-dark btn-primary font-weight-bold" style="position: relative; margin: 10px; background-color: #ff8d00;float: right" asp-area="" asp-controller="Admin" asp- asp-action="Get">Get All Products</a>
                                <script type="text/javascript">
                                                    window.onload = function () {
                                                    alert("@ViewBag.Message");
                                                    };
                                </script>
                            }
                        </div>*@
                    @*</div>*@
                </div>
            </div>
            <div class="col-4">
            </div>
        </div>
    </div>
</form>

EmployeeManagementSystem/Views/Users/Delete.cshtml
@*@{
        ViewData["Title"] = "Delete";
    }

    <h1>Delete</h1>*@

@model EmployeeManagementSystem.Models.User
@{
    ViewData["Title"] = "Delete";
}

<form method="post" asp-controller="Users" asp-action="Delete">
    @* <input asp-for="CompanyId" hidden />*@
    <div class="border p-3">
        <div class="form-group row">
            <h1 class="text-info p1-3">Delete User</h1>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Id"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Id" class="form-control" />
                        <span asp-validation-for="Id" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="UserName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="UserName" class="form-control" />
                        <span asp-validation-for="UserName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Password"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                </div>
              
                <div class="form-group row">
                    @*<div class="col-6 offset-4 row">*@
                    <div class="col-4 offset-4">
                        <input type="submit" class="btn btn-info w-100" value="Delete" />
                    </div>
                    <div class="col">
                        @if (ViewBag.Message != null)
                        {
                            @*<a class="nav-link text-dark btn-primary font-weight-bold" style="margin: 10px; background-color: #ffdd0f;top: 2px " asp-area="" asp-controller="Admin" asp- asp-action="Get">Get Employees</a>*@
                            <a class="nav-link text-dark btn-primary font-weight-bold" style="position: relative; margin: 10px; background-color: #ff8d00;float: right" asp-area="" asp-controller="Users" asp- asp-action="Get">Get User</a>
                            <script type="text/javascript">
                                                    window.onload = function () {
                                                    alert("@ViewBag.Message");
                                                    };
                            </script>
                        }
                    </div>
                    @*</div>*@
                </div>
            </div>
            <div class="col-4">
            </div>
        </div>
    </div>
</form>

EmployeeManagementSystem/Views/Users/Get.cshtml
@*@{
        ViewData["Title"] = "Get";
    }

    <h1>Get</h1>*@
@model IEnumerable<EmployeeManagementSystem.Models.User>

@{
    ViewData["Title"] = "Get";
}

<div style="position: absolute; top: 0; right: 0; width: 180px; text-align:right;">
    <button><h3><a class="nav-link text-dark btn-primary font-weight-bold" style="position: relative; margin: 10px; background-color: #FFFFFF; float: left" asp-area="" asp-controller="Account" asp-action="SignOut">User SignOut</a></h3></button>
</div>
<br />

<div class="col-6">
    <h2 class="text-primary">User List</h2>
</div>
<div class="container">
    <div class="btn-group">
        </h3><button type="button" class="nav-link text-dark btn-primary font-weight-bold" style="margin: 1px; background-color: #00b9ff;float: initial" asp-area="" asp-controller="Users" asp- asp-action="Get">User</button></h3>
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
            <a class="nav-link text-dark btn-primary font-weight-bold" style="background-color: #FFFFFF;float: left" asp-area="" asp-controller="Employees" asp- asp-action="Get">Employee</a>
            <a class="nav-link text-dark btn-primary font-weight-bold" style="background-color: #FFFFFF;float: left" asp-area="" asp-controller="Projects" asp- asp-action="Get"> Project</a>
            <a class="nav-link text-dark btn-primary font-weight-bold" style="background-color: #FFFFFF;float: left" asp-area="" asp-controller="Departments" asp- asp-action="Get"> Department</a>
            <a class="nav-link text-dark btn-primary font-weight-bold" style="background-color: #FFFFFF;float: left" asp-area="" asp-controller="Users" asp- asp-action="Get"> Companies</a>
        </ul>
    </div>
</div>

<div class="container p-3">
    <div class="row pt-10">
        @*<div class="col-6">
                <h4>Employee List</h4>
            </div >*@
        <div class="col-12">
            <a class="nav-link text-dark btn-primary font-weight-bold" style="margin: 10px; background-color: #00b9ff;float: right" asp-area="" asp-controller="Users" asp- asp-action="Create">Create New Users</a>
        </div>
    </div>
    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Id
                    </th>
                    <th>
                        UserName
                    </th>
                    <th>
                        Password
                    </th>


                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td width="10%">@obj.Id</td>
                        <td width="30%">@obj.UserName</td>
                        <td width="20%">@obj.Password</td>

                        <td class="text-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Users" asp-route-Id="@obj.Id" asp-action="update" class="btn btn-primary mx-1">
                                    <i class="fas fa-edit"></i> Edit
                                </a>
                                <a asp-controller="Users" asp-route-Id="@obj.Id" asp-action="Delete" class="btn btn-danger mx-3">
                                    <i class="far fa-trash-alt"></i> Delete
                                </a>
                            </div>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

EmployeeManagementSystem/Views/Users/update.cshtml
@*@{
        ViewData["Title"] = "update";
    }

    <h1>update</h1>*@

@model EmployeeManagementSystem.Models.User

@{
    ViewData["Title"] = "update";
}

<form method="post" asp-controller="Users" asp-action="update">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h1 class="text-info p1-3">Edit User</h1>
        </div>
        <div class="row">
            <div class="col-8">

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="UserName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="UserName" class="form-control" />
                        <span asp-validation-for="UserName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Password"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                </div>
                
                <div class="form-group row">
                    @*<div class="col-6 offset-4 row">*@
                    <div class="col-4 offset-4">
                        <input type="submit" class="btn btn-info w-100" value="Update" />
                    </div>
                    <div class="col">
                        @if (ViewBag.Message != null)
                        {
                            @*<a class="nav-link text-dark btn-primary font-weight-bold" style="margin: 10px; background-color: #ffdd0f;top: 2px " asp-area="" asp-controller="Admin" asp- asp-action="Get">Get Employees</a>*@
                            <a class="nav-link text-dark btn-primary font-weight-bold" style="position: relative; margin: 10px; background-color: #ff8d00;float: right" asp-area="" asp-controller="Users" asp- asp-action="Get">Get User</a>
                            <script type="text/javascript">
                                                    window.onload = function () {
                                                    alert("@ViewBag.Message");
                                                    };
                            </script>
                        }
                    </div>
                    @*</div>*@
                </div>
            </div>
            <div class="col-4">
            </div>
        </div>
    </div>
</form>