EmployeeManagementSystem/Models/Employees.cs
using System;
using System.ComponentModel.DataAnnotations;
namespace EmployeeManagementSystem.Models
{
    public class Employee
    {
        [Key]
        // [Required(ErrorMessage ="EmployeeId is required")]
        // [Range(minimum:1,maximum:20,ErrorMessage ="limit exceeded")]
        public int EmployeeId{get; set;}
        [Required]
        [StringLength(maximumLength:20, ErrorMessage ="Maximum length exceeded")]
        public string LastName{get; set;}
        [Required]
        [StringLength(maximumLength:10, ErrorMessage ="Maximum length exceeded")]
        public string FirstName{get; set;}
        public DateTime? BirthDate{get; set;}
        public DateTime? HireDate{get; set;}
        public string? Address{get; set;}
        public string? City{get; set;}
        public string? Region{get; set;}
        public int? PostalCode{get; set;}
        public string? Country{get; set;}
        public int? HomePhone{get; set;}
        public int? DepartmentId{get; set;}
        public int? ProjectId{get; set;}
    }
}

EmployeeManagementSystem/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using EmployeeManagementSystem.Models;
using EmployeeManagementSystem.Infrastructure;
using System.Security.Claims;
//using Microsoft.AspNetCore.Diagnostics;

namespace EmployeeManagementSystem.Controllers
{
    /*******************   CHANGED:  ******************************
Removed the Authorize attribute from here and moved it the  methods 
where the restrictions are required. 
******************************************************/
    public class EmployeesController : Controller
    {
        string userName;
        int userId;
        ICRUDRepository<Employee, int> _repository;
        public SendServiceBusMessage _SendServiceBusMessage;
        public EmployeesController(ICRUDRepository<Employee, int> repository, SendServiceBusMessage sendServiceBusMessage)
        {
            _repository = repository;
            _SendServiceBusMessage = sendServiceBusMessage;
        }
/************** CHANGES : ******************************************
* Add the Authorize attribute to the method 
* In the method, we are getting the Claim values like Name, NameIdentifier and Role 
* if the RoleName is not "admin" or any other role as required, 
*  then we are returning an Unauthorized() response back to the user.
* else valid response will be sent. 
********************************************************************/
        public ActionResult<IEnumerable<Employee>> Get()
        {
            try{
            var items = _repository.GetAll(); 
            return View(items);
            }
            catch(Exception ex)
            {
                throw;
            }
        }
        //URL: /api/employees/1   
        //try with id parameter values between 1 and 9 
        [HttpGet("{id}")]
        public ActionResult<Employee> GetDetails(int id) 
        {
            try{
            var  item = _repository.GetDetails(id);
            if( item==null )
                return NotFound();
            return item;
            }
            catch(Exception ex)
            {
                throw;
            }
        }
        // [HttpGet("employee")]
        // public Models.Employee GetEmployee()
        // {
        //     Models.Employee obj = new Models.Employee{
        //         EmployeeId= 12,
        //         FirstName = "RRR",
        //     };
        //     return obj;
        // }

        public IActionResult Create()
        {
            return View();
        }
        [Microsoft.AspNetCore.Authorization.Authorize()]

        [HttpPost]
        public async Task<ActionResult<Employee>> Create(Employee emp)
        {
            if(!ModelState.IsValid)
            //throw new ArgumentException("Not found");
            userName = HttpContext.User.FindFirst(ClaimTypes.Name).Value;
            userId = Convert.ToInt32("0" + HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var role = Convert.ToString(HttpContext.User.FindFirst(ClaimTypes.Role).Value);
            if(role!="newemployee") 
            {
                return Unauthorized();
            } 
            if(userId==0) return BadRequest();
            try{
            if(emp==null) return BadRequest();
            _repository.Create(emp);
                await _SendServiceBusMessage.sendServiceBusMessage(new ServiceBusMessageData
                {
                    FirstName = emp.FirstName,
                    action = "Add",
                    actionMessage = "Employee Added Successfully"
                });
            return View();
            }
            catch(Exception ex)
            {
                throw;
            }
        }

        public IActionResult update(int Id)
        {
            Employee emp = _repository.GetDetails(Id);
            if (emp == null)
            {
                return BadRequest();
            }
            else
            {
                return View(emp);
            }
        }
        [Microsoft.AspNetCore.Authorization.Authorize()]
        [HttpPost]
        public async Task<ActionResult<Employee>> update(Employee emp)
        {
            userName = HttpContext.User.FindFirst(ClaimTypes.Name).Value;
            userId = Convert.ToInt32("0" + HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var role = Convert.ToString(HttpContext.User.FindFirst(ClaimTypes.Role).Value);
            if(role!="employee"&&role!="admin")
            { 
                return Unauthorized();
            }
            if(userId==0) return BadRequest();
            //if(emp==null)   return BadRequest();
            try{
            if(emp==null)
                return BadRequest();
            _repository.update(emp);
                await _SendServiceBusMessage.sendServiceBusMessage(new ServiceBusMessageData
                {
                    FirstName = emp.FirstName,
                    action = "Update",
                    actionMessage = "Employee Updated Successfully"
                });
                ViewBag.Message = string.Format("Updated Successfully");
            return View(emp);
            }
            catch(Exception ex)
            {
                throw;
            }
        }

        public IActionResult Delete(int Id)
        {
            Employee emp = _repository.GetDetails(Id);
            if (emp == null)
            {
                return BadRequest();
            }
            else
            {
                return View(emp);
            }
        }


        //public IActionResult Delete()
        //{
        //    return View();
        //}


        [Microsoft.AspNetCore.Authorization.Authorize()]
        [HttpPost]
        public async Task <ActionResult<Employee>> Delete(int id,Employee emp)
        {
            userName = HttpContext.User.FindFirst(ClaimTypes.Name).Value;
            userId = Convert.ToInt32("0" + HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var role = Convert.ToString(HttpContext.User.FindFirst(ClaimTypes.Role).Value);
            if(role!="admin") 
            {
                return Unauthorized();
            }
            //end of the code inclusion. 
            if(userId==0) return BadRequest();
            try{
            _repository.Delete(id);
                await _SendServiceBusMessage.sendServiceBusMessage(new ServiceBusMessageData
                {
                    FirstName = emp.FirstName,
                    action = "Delete",
                    actionMessage = "Employee Deleted Successfully"
                });
                ViewBag.Message = string.Format("Deleted Successfully");
             return Redirect("/employees/Get");
        }
        catch(Exception ex)
            {
                throw;
            }
    
}
}
}

EmployeeManagementSystem/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using EmployeeManagementSystem.Models;
using EmployeeManagementSystem.Infrastructure;
using System.Security.Claims;



namespace EmployeeManagementSystem.Controllers
{
    public class UsersController : Controller
    {
        string userName;
        int userId;
        ICRUDRepository<User, int> _repository;
        public SendServiceBusMessage _SendServiceBusMessage;
        public UsersController(ICRUDRepository<User, int> repository, SendServiceBusMessage sendServiceBusMessage)
        {
            _repository = repository;
            _SendServiceBusMessage = sendServiceBusMessage;
        }
        public ActionResult<IEnumerable<User>> Get()
        {
            try
            {
                var items = _repository.GetAll();
                //return items.ToList();
                return View(items);
            }
            catch(Exception ex)
            {
                throw;
            }
        }

        // [HttpGet("Users")]
        // public Models.User GetUser()
        // {
        //     Models.User obj = new Models.User{
        //         Id=1,
        //         UserName="Jyo",
        //         UserAddress="Banglore",
        //         UserType="No",
        //         Password="AH6SKJ",
        //     };
        //    return obj;  
        // } 

             [HttpGet("{id}")]
           public ActionResult<User> GetDetails(int id)
           {
                try
                {
                    var item = _repository.GetDetails(id);
                    if (item == null)
                        return NotFound();

                    return item;
                }
                catch(Exception ex)
                {
                    throw;
                }

           }
        public IActionResult Create()
        {
            return View();
        }
        [Microsoft.AspNetCore.Authorization.Authorize()]

        [HttpPost]
        
           public async Task <ActionResult<User>> Create(User usr)
           {
            userName = HttpContext.User.FindFirst(ClaimTypes.Name).Value;
            userId = Convert.ToInt32("0" + HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var role = Convert.ToString(HttpContext.User.FindFirst(ClaimTypes.Role).Value);
                if(role!="newemployee") 
                {
                    return Unauthorized();
                }
                try
               { 
                    if(userId==0) return BadRequest();
                       if(usr==null)
                       return BadRequest();

                   _repository.Create(usr);

                    await _SendServiceBusMessage.sendServiceBusMessage(new ServiceBusMessageData
                    {
                        UserName = usr.UserName,
                        action = "Create",
                        actionMessage = "User Created Successfully"
                    });
                    return Redirect("/Users/Get");
                }
                catch (Exception ex)
                {
                    throw;
                }
                   return usr;
    
               
           } 

           //[HttpPut("update/{id}")]
        public IActionResult update(int Id)
        {
            User usr = _repository.GetDetails(Id);
            if (usr == null)
            {
                return BadRequest();
            }
            else
            {
                return View(usr);
            }
        }
        [Microsoft.AspNetCore.Authorization.Authorize()]

        [HttpPost]
          public async Task <ActionResult<User>> update(int id,User usr)
           {

                userName = HttpContext.User.FindFirst(ClaimTypes.Name).Value;
                userId = Convert.ToInt32("0" + HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
                var role = Convert.ToString(HttpContext.User.FindFirst(ClaimTypes.Role).Value);
                if (role != "admin")
                {
                    return Unauthorized();
                }
                if (userId == 0) return BadRequest();
            // if(id==0)  return BadRequest();
                try
                {
                    if (usr == null)
                        return BadRequest();
                    if (id == 0) return BadRequest();
                    _repository.update(usr);
                    await _SendServiceBusMessage.sendServiceBusMessage(new ServiceBusMessageData
                    {
                        UserName = usr.UserName,
                        action = "update",
                        actionMessage = "User Updated Successfully"
                    });
                    ViewBag.Message = string.Format("Updated Successfully");
                    return View(usr);
                }
                catch (Exception ex)
                   {
                        throw;
                 }
                    
                
           
          }
            //[HttpDelete("remove/{id}")]

        public IActionResult Delete(int Id)
        {
            User usr = _repository.GetDetails(Id);
            if (usr == null)
            {
                return BadRequest();
            }
            else
            {
                return View(usr);
            }
        }
        [Microsoft.AspNetCore.Authorization.Authorize()]
        [HttpPost]
         public async Task <ActionResult<User>> Delete(int id, User usr)
           {
                userName = HttpContext.User.FindFirst(ClaimTypes.Name).Value;
                userId = Convert.ToInt32("0" + HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
                var role = Convert.ToString(HttpContext.User.FindFirst(ClaimTypes.Role).Value);
                if(role!="admin") 
                {
                    return Unauthorized();
                }
                if(userId==0) return BadRequest();
                try
               { 
                       _repository.Delete(id);
                    await _SendServiceBusMessage.sendServiceBusMessage(new ServiceBusMessageData
                    {
                        UserName = usr.UserName,
                        action = "Delete",
                        actionMessage = "User Deleted Successfully"
                    });
                    ViewBag.Message = string.Format("User Deleted Successfully");
                    return Redirect("/Users/Get");
               }
                catch (Exception ex)
                {
                    throw;
                }
               // return Ok();
           
           }

        
    }
}

EmployeeManagementSystem/Views/Employees/Create.cshtml
@model EmployeeManagementSystem.Models.Employee

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<form method="post" asp-controller="Employees" asp-action="Create">
    <div class="border p-3">
        <div class="form-group row">
            <h1 class="text-info p1-3">Add Employee</h1>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="FirstName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="LastName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="BirthDate"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="BirthDate" class="form-control" />
                        <span asp-validation-for="BirthDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="HireDate"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="HireDate" class="form-control" />
                        <span asp-validation-for="HireDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Address"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="City"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="City" class="form-control" />
                        <span asp-validation-for="City" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Region"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Region" class="form-control" />
                        <span asp-validation-for="Region" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="PostalCode"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="PostalCode" class="form-control" />
                        <span asp-validation-for="PostalCode" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Country"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Country" class="form-control" />
                        <span asp-validation-for="Country" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="HomePhone"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="HomePhone" class="form-control" />
                        <span asp-validation-for="HomePhone" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="DepartmentId"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DepartmentId" class="form-control" />
                        <span asp-validation-for="DepartmentId" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="ProjectId"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="ProjectId" class="form-control" />
                        <span asp-validation-for="ProjectId" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    @*<div class="col-6 offset-4 row">*@
                    <div class="col-4 offset-4">
                        <input type="submit" class="btn btn-info w-100" value="Add" />
                    </div>
                    @*<div class="col">
                        @if (ViewBag.Message != null)
                        {
                            //<a class="nav-link text-dark btn-primary font-weight-bold" style="margin: 10px; background-color: #ffdd0f;top: 2px " asp-area="" asp-controller="Admin" asp- asp-action="Get">Get All Products</a>
                            <a class="nav-link text-dark btn-primary font-weight-bold" style="position: relative; margin: 10px; background-color: #ff8d00;float: right" asp-area="" asp-controller="Admin" asp- asp-action="Get">Get All Products</a>
                            <script type="text/javascript">
                                                window.onload = function () {
                                                alert("@ViewBag.Message");
                                                };
                            </script>
                        }
                    </div>*@
                    @*</div>*@
                </div>
            </div>
            <div class="col-4">
            </div>
        </div>
    </div>
</form>

EmployeeManagementSystem/Views/Employees/Get.cshtml
@model IEnumerable<EmployeeManagementSystem.Models.Employee>

@{
    ViewData["Title"] = "Employee";
}

<div style="position: absolute; top: 0; right: 0; width: 180px; text-align:right;">
    <button><h3><a class="nav-link text-dark btn-primary font-weight-bold" style="position: relative; margin: 10px; background-color: #FFFFFF; float: left" asp-area="" asp-controller="Account" asp-action="SignOut">Employee SignOut</a></h3></button>
</div><br />

@*<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <h2><a class="nav-link text-dark btn-primary font-weight-bold" style="position: relative; margin: 10px; background-color: #FFFFFF; float: left" asp-area="" asp-controller="Account" asp-action="SignOut">Employee</a></h2>
    </ul>*@
</div>

<div class="col-6">
    <h2 class="text-primary">Employees List</h2>
</div>
<div class="container">
    <div class="btn-group">
        </h3><button type="button" class="nav-link text-dark btn-primary font-weight-bold" style="margin: 1px; background-color: #00b9ff;float: initial" asp-area="" asp-controller="Employees" asp- asp-action="Get">Employee</button></h3>
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
            <a class="nav-link text-dark btn-primary font-weight-bold" style="background-color: #FFFFFF;float: left" asp-area="" asp-controller="Companies" asp- asp-action="Get">Company</a>
            <a class="nav-link text-dark btn-primary font-weight-bold" style="background-color: #FFFFFF;float: left" asp-area="" asp-controller="Projects" asp- asp-action="Get"> Project</a>
            <a class="nav-link text-dark btn-primary font-weight-bold" style="background-color: #FFFFFF;float: left" asp-area="" asp-controller="Departments" asp- asp-action="Get">Department</a>
            <a class="nav-link text-dark btn-primary font-weight-bold" style="background-color: #FFFFFF;float: left" asp-area="" asp-controller="Users" asp- asp-action="Get"> User</a>
        </ul>
    </div>
</div>
<div class="container p-3">
    <div class="row pt-10">
        @*<div class="col-6">
                <h4>Employee List</h4>
            </div >*@
        <div class="col-12">
            </h3><a class="nav-link text-dark btn-primary font-weight-bold" style="margin: 10px; background-color: #00b9ff;float: right" asp-area="" asp-controller="Employees" asp- asp-action="Create">Register</a></h3>
        </div>
        <div class="btn-group-vertical">
            @*   <div class="col-12">
                        <a class="nav-link text-dark btn-primary font-weight-bold" style="margin: 10px; background-color: #00b9ff;float: left" asp-area="" asp-controller="Companies" asp- asp-action="Get">Company</a>
                        <a class="nav-link text-dark btn-primary font-weight-bold" style="margin: 10px; background-color: #00b9ff;float: left" asp-area="" asp-controller="Projects" asp- asp-action="Get">Project</a>

                    </div>
                </div>*@

            @if (Model.Count() > 0)
            {
                <table class="table table-bordered table-striped" style="width:100%">
                    <thead>
                        <tr>
                            <th>
                                EmployeeId
                            </th>
                            <th>
                                FirstName
                            </th>
                            <th>
                                LastName
                            </th>
                            <th>
                                BirthDate
                            </th>
                            <th>
                                HireDate
                            </th>
                            <th>
                                Address
                            </th>
                            <th>
                                City
                            </th>
                            <th>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var obj in Model)
                        {
                            <tr>
                                <td width="10%">@obj.EmployeeId</td>
                                <td width="30%">@obj.FirstName</td>
                                <td width="20%">@obj.LastName</td>
                                <td width="20%">@obj.BirthDate</td>
                                <td width="10%">@obj.HireDate</td>
                                <td width="40%">@obj.Address</td>
                                <td width="40%">@obj.City</td>
                                <td class="text-center">
                                    <div class="w-75 btn-group" role="group">
                                        <a asp-controller="Employees" asp-route-Id="@obj.EmployeeId" asp-action="update" class="btn btn-primary mx-1">
                                            <i class="fas fa-edit"></i> Edit
                                        </a>
                                        <a asp-controller="Employees" asp-route-Id="@obj.EmployeeId" asp-action="Delete" class="btn btn-danger mx-3">
                                            <i class="far fa-trash-alt"></i> Delete
                                        </a>
                                    </div>
                            </tr>
                        }
                    </tbody>
                </table>
            }
        </div>